[project]
name = "1320"
version = "0.1.0"
description = "Video streaming for videos on jw.org"

readme = "README.md"
requires-python = ">=3.10"

[project.dependencies]
dependencies = "requirements.txt"

[tool.flake8]
max-line-length = 88
exclude = ["__pycache__", "static", "templates"]
